name: will scan terraform code with terrscan github action on push
on: 
  push:
    branches:
      - "main"

jobs:
  terrascan_action:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run Terrascan action
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        
